services:
  - type: web
    name: wave-room-chat
    runtime: ruby
    rootDir: chatroom-app
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec ruby server.rb
    envVars:
      - key: STORAGE_ROOT
        value: /opt/render/project/src/chatroom-app/storage
